FROM oven/bun:1-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./

RUN bun install --frozen-lockfile

COPY . .

RUN bunx prisma generate
RUN bun lint # check for errors
RUN bun tsc --noEmit # type check
RUN bun build ./src/index.ts --outdir ./dist --target=bun

FROM oven/bun:1-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./

RUN bun install --frozen-lockfile --production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["bun", "run", "dist/index.js"]
