
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Subgroup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Subgroup
 * 
 */
export type SubgroupModel = runtime.Types.Result.DefaultSelection<Prisma.$SubgroupPayload>

export type AggregateSubgroup = {
  _count: SubgroupCountAggregateOutputType | null
  _min: SubgroupMinAggregateOutputType | null
  _max: SubgroupMaxAggregateOutputType | null
}

export type SubgroupMinAggregateOutputType = {
  id: string | null
  name: string | null
  theme: string | null
  communityId: string | null
  rainbowBubbleId: string | null
  createdAt: Date | null
}

export type SubgroupMaxAggregateOutputType = {
  id: string | null
  name: string | null
  theme: string | null
  communityId: string | null
  rainbowBubbleId: string | null
  createdAt: Date | null
}

export type SubgroupCountAggregateOutputType = {
  id: number
  name: number
  theme: number
  communityId: number
  rainbowBubbleId: number
  createdAt: number
  _all: number
}


export type SubgroupMinAggregateInputType = {
  id?: true
  name?: true
  theme?: true
  communityId?: true
  rainbowBubbleId?: true
  createdAt?: true
}

export type SubgroupMaxAggregateInputType = {
  id?: true
  name?: true
  theme?: true
  communityId?: true
  rainbowBubbleId?: true
  createdAt?: true
}

export type SubgroupCountAggregateInputType = {
  id?: true
  name?: true
  theme?: true
  communityId?: true
  rainbowBubbleId?: true
  createdAt?: true
  _all?: true
}

export type SubgroupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Subgroup to aggregate.
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subgroups to fetch.
   */
  orderBy?: Prisma.SubgroupOrderByWithRelationInput | Prisma.SubgroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubgroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subgroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subgroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Subgroups
  **/
  _count?: true | SubgroupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubgroupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubgroupMaxAggregateInputType
}

export type GetSubgroupAggregateType<T extends SubgroupAggregateArgs> = {
      [P in keyof T & keyof AggregateSubgroup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubgroup[P]>
    : Prisma.GetScalarType<T[P], AggregateSubgroup[P]>
}




export type SubgroupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubgroupWhereInput
  orderBy?: Prisma.SubgroupOrderByWithAggregationInput | Prisma.SubgroupOrderByWithAggregationInput[]
  by: Prisma.SubgroupScalarFieldEnum[] | Prisma.SubgroupScalarFieldEnum
  having?: Prisma.SubgroupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubgroupCountAggregateInputType | true
  _min?: SubgroupMinAggregateInputType
  _max?: SubgroupMaxAggregateInputType
}

export type SubgroupGroupByOutputType = {
  id: string
  name: string
  theme: string | null
  communityId: string
  rainbowBubbleId: string
  createdAt: Date
  _count: SubgroupCountAggregateOutputType | null
  _min: SubgroupMinAggregateOutputType | null
  _max: SubgroupMaxAggregateOutputType | null
}

export type GetSubgroupGroupByPayload<T extends SubgroupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubgroupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubgroupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubgroupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubgroupGroupByOutputType[P]>
      }
    >
  >



export type SubgroupWhereInput = {
  AND?: Prisma.SubgroupWhereInput | Prisma.SubgroupWhereInput[]
  OR?: Prisma.SubgroupWhereInput[]
  NOT?: Prisma.SubgroupWhereInput | Prisma.SubgroupWhereInput[]
  id?: Prisma.StringFilter<"Subgroup"> | string
  name?: Prisma.StringFilter<"Subgroup"> | string
  theme?: Prisma.StringNullableFilter<"Subgroup"> | string | null
  communityId?: Prisma.StringFilter<"Subgroup"> | string
  rainbowBubbleId?: Prisma.StringFilter<"Subgroup"> | string
  createdAt?: Prisma.DateTimeFilter<"Subgroup"> | Date | string
  community?: Prisma.XOR<Prisma.CommunityScalarRelationFilter, Prisma.CommunityWhereInput>
  knowledgeItems?: Prisma.KnowledgeItemListRelationFilter
}

export type SubgroupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  theme?: Prisma.SortOrderInput | Prisma.SortOrder
  communityId?: Prisma.SortOrder
  rainbowBubbleId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  community?: Prisma.CommunityOrderByWithRelationInput
  knowledgeItems?: Prisma.KnowledgeItemOrderByRelationAggregateInput
}

export type SubgroupWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  rainbowBubbleId?: string
  AND?: Prisma.SubgroupWhereInput | Prisma.SubgroupWhereInput[]
  OR?: Prisma.SubgroupWhereInput[]
  NOT?: Prisma.SubgroupWhereInput | Prisma.SubgroupWhereInput[]
  name?: Prisma.StringFilter<"Subgroup"> | string
  theme?: Prisma.StringNullableFilter<"Subgroup"> | string | null
  communityId?: Prisma.StringFilter<"Subgroup"> | string
  createdAt?: Prisma.DateTimeFilter<"Subgroup"> | Date | string
  community?: Prisma.XOR<Prisma.CommunityScalarRelationFilter, Prisma.CommunityWhereInput>
  knowledgeItems?: Prisma.KnowledgeItemListRelationFilter
}, "id" | "rainbowBubbleId">

export type SubgroupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  theme?: Prisma.SortOrderInput | Prisma.SortOrder
  communityId?: Prisma.SortOrder
  rainbowBubbleId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SubgroupCountOrderByAggregateInput
  _max?: Prisma.SubgroupMaxOrderByAggregateInput
  _min?: Prisma.SubgroupMinOrderByAggregateInput
}

export type SubgroupScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubgroupScalarWhereWithAggregatesInput | Prisma.SubgroupScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubgroupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubgroupScalarWhereWithAggregatesInput | Prisma.SubgroupScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Subgroup"> | string
  name?: Prisma.StringWithAggregatesFilter<"Subgroup"> | string
  theme?: Prisma.StringNullableWithAggregatesFilter<"Subgroup"> | string | null
  communityId?: Prisma.StringWithAggregatesFilter<"Subgroup"> | string
  rainbowBubbleId?: Prisma.StringWithAggregatesFilter<"Subgroup"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Subgroup"> | Date | string
}

export type SubgroupCreateInput = {
  id?: string
  name: string
  theme?: string | null
  rainbowBubbleId: string
  createdAt?: Date | string
  community: Prisma.CommunityCreateNestedOneWithoutSubgroupsInput
  knowledgeItems?: Prisma.KnowledgeItemCreateNestedManyWithoutSubgroupInput
}

export type SubgroupUncheckedCreateInput = {
  id?: string
  name: string
  theme?: string | null
  communityId: string
  rainbowBubbleId: string
  createdAt?: Date | string
  knowledgeItems?: Prisma.KnowledgeItemUncheckedCreateNestedManyWithoutSubgroupInput
}

export type SubgroupUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  community?: Prisma.CommunityUpdateOneRequiredWithoutSubgroupsNestedInput
  knowledgeItems?: Prisma.KnowledgeItemUpdateManyWithoutSubgroupNestedInput
}

export type SubgroupUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  communityId?: Prisma.StringFieldUpdateOperationsInput | string
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  knowledgeItems?: Prisma.KnowledgeItemUncheckedUpdateManyWithoutSubgroupNestedInput
}

export type SubgroupCreateManyInput = {
  id?: string
  name: string
  theme?: string | null
  communityId: string
  rainbowBubbleId: string
  createdAt?: Date | string
}

export type SubgroupUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubgroupUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  communityId?: Prisma.StringFieldUpdateOperationsInput | string
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubgroupListRelationFilter = {
  every?: Prisma.SubgroupWhereInput
  some?: Prisma.SubgroupWhereInput
  none?: Prisma.SubgroupWhereInput
}

export type SubgroupOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubgroupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  theme?: Prisma.SortOrder
  communityId?: Prisma.SortOrder
  rainbowBubbleId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubgroupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  theme?: Prisma.SortOrder
  communityId?: Prisma.SortOrder
  rainbowBubbleId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubgroupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  theme?: Prisma.SortOrder
  communityId?: Prisma.SortOrder
  rainbowBubbleId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubgroupScalarRelationFilter = {
  is?: Prisma.SubgroupWhereInput
  isNot?: Prisma.SubgroupWhereInput
}

export type SubgroupCreateNestedManyWithoutCommunityInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput> | Prisma.SubgroupCreateWithoutCommunityInput[] | Prisma.SubgroupUncheckedCreateWithoutCommunityInput[]
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutCommunityInput | Prisma.SubgroupCreateOrConnectWithoutCommunityInput[]
  createMany?: Prisma.SubgroupCreateManyCommunityInputEnvelope
  connect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
}

export type SubgroupUncheckedCreateNestedManyWithoutCommunityInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput> | Prisma.SubgroupCreateWithoutCommunityInput[] | Prisma.SubgroupUncheckedCreateWithoutCommunityInput[]
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutCommunityInput | Prisma.SubgroupCreateOrConnectWithoutCommunityInput[]
  createMany?: Prisma.SubgroupCreateManyCommunityInputEnvelope
  connect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
}

export type SubgroupUpdateManyWithoutCommunityNestedInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput> | Prisma.SubgroupCreateWithoutCommunityInput[] | Prisma.SubgroupUncheckedCreateWithoutCommunityInput[]
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutCommunityInput | Prisma.SubgroupCreateOrConnectWithoutCommunityInput[]
  upsert?: Prisma.SubgroupUpsertWithWhereUniqueWithoutCommunityInput | Prisma.SubgroupUpsertWithWhereUniqueWithoutCommunityInput[]
  createMany?: Prisma.SubgroupCreateManyCommunityInputEnvelope
  set?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  disconnect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  delete?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  connect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  update?: Prisma.SubgroupUpdateWithWhereUniqueWithoutCommunityInput | Prisma.SubgroupUpdateWithWhereUniqueWithoutCommunityInput[]
  updateMany?: Prisma.SubgroupUpdateManyWithWhereWithoutCommunityInput | Prisma.SubgroupUpdateManyWithWhereWithoutCommunityInput[]
  deleteMany?: Prisma.SubgroupScalarWhereInput | Prisma.SubgroupScalarWhereInput[]
}

export type SubgroupUncheckedUpdateManyWithoutCommunityNestedInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput> | Prisma.SubgroupCreateWithoutCommunityInput[] | Prisma.SubgroupUncheckedCreateWithoutCommunityInput[]
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutCommunityInput | Prisma.SubgroupCreateOrConnectWithoutCommunityInput[]
  upsert?: Prisma.SubgroupUpsertWithWhereUniqueWithoutCommunityInput | Prisma.SubgroupUpsertWithWhereUniqueWithoutCommunityInput[]
  createMany?: Prisma.SubgroupCreateManyCommunityInputEnvelope
  set?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  disconnect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  delete?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  connect?: Prisma.SubgroupWhereUniqueInput | Prisma.SubgroupWhereUniqueInput[]
  update?: Prisma.SubgroupUpdateWithWhereUniqueWithoutCommunityInput | Prisma.SubgroupUpdateWithWhereUniqueWithoutCommunityInput[]
  updateMany?: Prisma.SubgroupUpdateManyWithWhereWithoutCommunityInput | Prisma.SubgroupUpdateManyWithWhereWithoutCommunityInput[]
  deleteMany?: Prisma.SubgroupScalarWhereInput | Prisma.SubgroupScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type SubgroupCreateNestedOneWithoutKnowledgeItemsInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedCreateWithoutKnowledgeItemsInput>
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutKnowledgeItemsInput
  connect?: Prisma.SubgroupWhereUniqueInput
}

export type SubgroupUpdateOneRequiredWithoutKnowledgeItemsNestedInput = {
  create?: Prisma.XOR<Prisma.SubgroupCreateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedCreateWithoutKnowledgeItemsInput>
  connectOrCreate?: Prisma.SubgroupCreateOrConnectWithoutKnowledgeItemsInput
  upsert?: Prisma.SubgroupUpsertWithoutKnowledgeItemsInput
  connect?: Prisma.SubgroupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubgroupUpdateToOneWithWhereWithoutKnowledgeItemsInput, Prisma.SubgroupUpdateWithoutKnowledgeItemsInput>, Prisma.SubgroupUncheckedUpdateWithoutKnowledgeItemsInput>
}

export type SubgroupCreateWithoutCommunityInput = {
  id?: string
  name: string
  theme?: string | null
  rainbowBubbleId: string
  createdAt?: Date | string
  knowledgeItems?: Prisma.KnowledgeItemCreateNestedManyWithoutSubgroupInput
}

export type SubgroupUncheckedCreateWithoutCommunityInput = {
  id?: string
  name: string
  theme?: string | null
  rainbowBubbleId: string
  createdAt?: Date | string
  knowledgeItems?: Prisma.KnowledgeItemUncheckedCreateNestedManyWithoutSubgroupInput
}

export type SubgroupCreateOrConnectWithoutCommunityInput = {
  where: Prisma.SubgroupWhereUniqueInput
  create: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput>
}

export type SubgroupCreateManyCommunityInputEnvelope = {
  data: Prisma.SubgroupCreateManyCommunityInput | Prisma.SubgroupCreateManyCommunityInput[]
  skipDuplicates?: boolean
}

export type SubgroupUpsertWithWhereUniqueWithoutCommunityInput = {
  where: Prisma.SubgroupWhereUniqueInput
  update: Prisma.XOR<Prisma.SubgroupUpdateWithoutCommunityInput, Prisma.SubgroupUncheckedUpdateWithoutCommunityInput>
  create: Prisma.XOR<Prisma.SubgroupCreateWithoutCommunityInput, Prisma.SubgroupUncheckedCreateWithoutCommunityInput>
}

export type SubgroupUpdateWithWhereUniqueWithoutCommunityInput = {
  where: Prisma.SubgroupWhereUniqueInput
  data: Prisma.XOR<Prisma.SubgroupUpdateWithoutCommunityInput, Prisma.SubgroupUncheckedUpdateWithoutCommunityInput>
}

export type SubgroupUpdateManyWithWhereWithoutCommunityInput = {
  where: Prisma.SubgroupScalarWhereInput
  data: Prisma.XOR<Prisma.SubgroupUpdateManyMutationInput, Prisma.SubgroupUncheckedUpdateManyWithoutCommunityInput>
}

export type SubgroupScalarWhereInput = {
  AND?: Prisma.SubgroupScalarWhereInput | Prisma.SubgroupScalarWhereInput[]
  OR?: Prisma.SubgroupScalarWhereInput[]
  NOT?: Prisma.SubgroupScalarWhereInput | Prisma.SubgroupScalarWhereInput[]
  id?: Prisma.StringFilter<"Subgroup"> | string
  name?: Prisma.StringFilter<"Subgroup"> | string
  theme?: Prisma.StringNullableFilter<"Subgroup"> | string | null
  communityId?: Prisma.StringFilter<"Subgroup"> | string
  rainbowBubbleId?: Prisma.StringFilter<"Subgroup"> | string
  createdAt?: Prisma.DateTimeFilter<"Subgroup"> | Date | string
}

export type SubgroupCreateWithoutKnowledgeItemsInput = {
  id?: string
  name: string
  theme?: string | null
  rainbowBubbleId: string
  createdAt?: Date | string
  community: Prisma.CommunityCreateNestedOneWithoutSubgroupsInput
}

export type SubgroupUncheckedCreateWithoutKnowledgeItemsInput = {
  id?: string
  name: string
  theme?: string | null
  communityId: string
  rainbowBubbleId: string
  createdAt?: Date | string
}

export type SubgroupCreateOrConnectWithoutKnowledgeItemsInput = {
  where: Prisma.SubgroupWhereUniqueInput
  create: Prisma.XOR<Prisma.SubgroupCreateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedCreateWithoutKnowledgeItemsInput>
}

export type SubgroupUpsertWithoutKnowledgeItemsInput = {
  update: Prisma.XOR<Prisma.SubgroupUpdateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedUpdateWithoutKnowledgeItemsInput>
  create: Prisma.XOR<Prisma.SubgroupCreateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedCreateWithoutKnowledgeItemsInput>
  where?: Prisma.SubgroupWhereInput
}

export type SubgroupUpdateToOneWithWhereWithoutKnowledgeItemsInput = {
  where?: Prisma.SubgroupWhereInput
  data: Prisma.XOR<Prisma.SubgroupUpdateWithoutKnowledgeItemsInput, Prisma.SubgroupUncheckedUpdateWithoutKnowledgeItemsInput>
}

export type SubgroupUpdateWithoutKnowledgeItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  community?: Prisma.CommunityUpdateOneRequiredWithoutSubgroupsNestedInput
}

export type SubgroupUncheckedUpdateWithoutKnowledgeItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  communityId?: Prisma.StringFieldUpdateOperationsInput | string
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubgroupCreateManyCommunityInput = {
  id?: string
  name: string
  theme?: string | null
  rainbowBubbleId: string
  createdAt?: Date | string
}

export type SubgroupUpdateWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  knowledgeItems?: Prisma.KnowledgeItemUpdateManyWithoutSubgroupNestedInput
}

export type SubgroupUncheckedUpdateWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  knowledgeItems?: Prisma.KnowledgeItemUncheckedUpdateManyWithoutSubgroupNestedInput
}

export type SubgroupUncheckedUpdateManyWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  theme?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rainbowBubbleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SubgroupCountOutputType
 */

export type SubgroupCountOutputType = {
  knowledgeItems: number
}

export type SubgroupCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  knowledgeItems?: boolean | SubgroupCountOutputTypeCountKnowledgeItemsArgs
}

/**
 * SubgroupCountOutputType without action
 */
export type SubgroupCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubgroupCountOutputType
   */
  select?: Prisma.SubgroupCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SubgroupCountOutputType without action
 */
export type SubgroupCountOutputTypeCountKnowledgeItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KnowledgeItemWhereInput
}


export type SubgroupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  theme?: boolean
  communityId?: boolean
  rainbowBubbleId?: boolean
  createdAt?: boolean
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
  knowledgeItems?: boolean | Prisma.Subgroup$knowledgeItemsArgs<ExtArgs>
  _count?: boolean | Prisma.SubgroupCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subgroup"]>

export type SubgroupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  theme?: boolean
  communityId?: boolean
  rainbowBubbleId?: boolean
  createdAt?: boolean
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subgroup"]>

export type SubgroupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  theme?: boolean
  communityId?: boolean
  rainbowBubbleId?: boolean
  createdAt?: boolean
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subgroup"]>

export type SubgroupSelectScalar = {
  id?: boolean
  name?: boolean
  theme?: boolean
  communityId?: boolean
  rainbowBubbleId?: boolean
  createdAt?: boolean
}

export type SubgroupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "theme" | "communityId" | "rainbowBubbleId" | "createdAt", ExtArgs["result"]["subgroup"]>
export type SubgroupInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
  knowledgeItems?: boolean | Prisma.Subgroup$knowledgeItemsArgs<ExtArgs>
  _count?: boolean | Prisma.SubgroupCountOutputTypeDefaultArgs<ExtArgs>
}
export type SubgroupIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
}
export type SubgroupIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>
}

export type $SubgroupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Subgroup"
  objects: {
    community: Prisma.$CommunityPayload<ExtArgs>
    knowledgeItems: Prisma.$KnowledgeItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    theme: string | null
    communityId: string
    rainbowBubbleId: string
    createdAt: Date
  }, ExtArgs["result"]["subgroup"]>
  composites: {}
}

export type SubgroupGetPayload<S extends boolean | null | undefined | SubgroupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubgroupPayload, S>

export type SubgroupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubgroupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubgroupCountAggregateInputType | true
  }

export interface SubgroupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Subgroup'], meta: { name: 'Subgroup' } }
  /**
   * Find zero or one Subgroup that matches the filter.
   * @param {SubgroupFindUniqueArgs} args - Arguments to find a Subgroup
   * @example
   * // Get one Subgroup
   * const subgroup = await prisma.subgroup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubgroupFindUniqueArgs>(args: Prisma.SelectSubset<T, SubgroupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Subgroup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubgroupFindUniqueOrThrowArgs} args - Arguments to find a Subgroup
   * @example
   * // Get one Subgroup
   * const subgroup = await prisma.subgroup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubgroupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubgroupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Subgroup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupFindFirstArgs} args - Arguments to find a Subgroup
   * @example
   * // Get one Subgroup
   * const subgroup = await prisma.subgroup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubgroupFindFirstArgs>(args?: Prisma.SelectSubset<T, SubgroupFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Subgroup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupFindFirstOrThrowArgs} args - Arguments to find a Subgroup
   * @example
   * // Get one Subgroup
   * const subgroup = await prisma.subgroup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubgroupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubgroupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Subgroups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Subgroups
   * const subgroups = await prisma.subgroup.findMany()
   * 
   * // Get first 10 Subgroups
   * const subgroups = await prisma.subgroup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const subgroupWithIdOnly = await prisma.subgroup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubgroupFindManyArgs>(args?: Prisma.SelectSubset<T, SubgroupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Subgroup.
   * @param {SubgroupCreateArgs} args - Arguments to create a Subgroup.
   * @example
   * // Create one Subgroup
   * const Subgroup = await prisma.subgroup.create({
   *   data: {
   *     // ... data to create a Subgroup
   *   }
   * })
   * 
   */
  create<T extends SubgroupCreateArgs>(args: Prisma.SelectSubset<T, SubgroupCreateArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Subgroups.
   * @param {SubgroupCreateManyArgs} args - Arguments to create many Subgroups.
   * @example
   * // Create many Subgroups
   * const subgroup = await prisma.subgroup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubgroupCreateManyArgs>(args?: Prisma.SelectSubset<T, SubgroupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Subgroups and returns the data saved in the database.
   * @param {SubgroupCreateManyAndReturnArgs} args - Arguments to create many Subgroups.
   * @example
   * // Create many Subgroups
   * const subgroup = await prisma.subgroup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Subgroups and only return the `id`
   * const subgroupWithIdOnly = await prisma.subgroup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubgroupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubgroupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Subgroup.
   * @param {SubgroupDeleteArgs} args - Arguments to delete one Subgroup.
   * @example
   * // Delete one Subgroup
   * const Subgroup = await prisma.subgroup.delete({
   *   where: {
   *     // ... filter to delete one Subgroup
   *   }
   * })
   * 
   */
  delete<T extends SubgroupDeleteArgs>(args: Prisma.SelectSubset<T, SubgroupDeleteArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Subgroup.
   * @param {SubgroupUpdateArgs} args - Arguments to update one Subgroup.
   * @example
   * // Update one Subgroup
   * const subgroup = await prisma.subgroup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubgroupUpdateArgs>(args: Prisma.SelectSubset<T, SubgroupUpdateArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Subgroups.
   * @param {SubgroupDeleteManyArgs} args - Arguments to filter Subgroups to delete.
   * @example
   * // Delete a few Subgroups
   * const { count } = await prisma.subgroup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubgroupDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubgroupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Subgroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Subgroups
   * const subgroup = await prisma.subgroup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubgroupUpdateManyArgs>(args: Prisma.SelectSubset<T, SubgroupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Subgroups and returns the data updated in the database.
   * @param {SubgroupUpdateManyAndReturnArgs} args - Arguments to update many Subgroups.
   * @example
   * // Update many Subgroups
   * const subgroup = await prisma.subgroup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Subgroups and only return the `id`
   * const subgroupWithIdOnly = await prisma.subgroup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubgroupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubgroupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Subgroup.
   * @param {SubgroupUpsertArgs} args - Arguments to update or create a Subgroup.
   * @example
   * // Update or create a Subgroup
   * const subgroup = await prisma.subgroup.upsert({
   *   create: {
   *     // ... data to create a Subgroup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Subgroup we want to update
   *   }
   * })
   */
  upsert<T extends SubgroupUpsertArgs>(args: Prisma.SelectSubset<T, SubgroupUpsertArgs<ExtArgs>>): Prisma.Prisma__SubgroupClient<runtime.Types.Result.GetResult<Prisma.$SubgroupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Subgroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupCountArgs} args - Arguments to filter Subgroups to count.
   * @example
   * // Count the number of Subgroups
   * const count = await prisma.subgroup.count({
   *   where: {
   *     // ... the filter for the Subgroups we want to count
   *   }
   * })
  **/
  count<T extends SubgroupCountArgs>(
    args?: Prisma.Subset<T, SubgroupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubgroupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Subgroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubgroupAggregateArgs>(args: Prisma.Subset<T, SubgroupAggregateArgs>): Prisma.PrismaPromise<GetSubgroupAggregateType<T>>

  /**
   * Group by Subgroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubgroupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubgroupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubgroupGroupByArgs['orderBy'] }
      : { orderBy?: SubgroupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubgroupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubgroupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Subgroup model
 */
readonly fields: SubgroupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Subgroup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubgroupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  community<T extends Prisma.CommunityDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CommunityDefaultArgs<ExtArgs>>): Prisma.Prisma__CommunityClient<runtime.Types.Result.GetResult<Prisma.$CommunityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  knowledgeItems<T extends Prisma.Subgroup$knowledgeItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Subgroup$knowledgeItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KnowledgeItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Subgroup model
 */
export interface SubgroupFieldRefs {
  readonly id: Prisma.FieldRef<"Subgroup", 'String'>
  readonly name: Prisma.FieldRef<"Subgroup", 'String'>
  readonly theme: Prisma.FieldRef<"Subgroup", 'String'>
  readonly communityId: Prisma.FieldRef<"Subgroup", 'String'>
  readonly rainbowBubbleId: Prisma.FieldRef<"Subgroup", 'String'>
  readonly createdAt: Prisma.FieldRef<"Subgroup", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Subgroup findUnique
 */
export type SubgroupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter, which Subgroup to fetch.
   */
  where: Prisma.SubgroupWhereUniqueInput
}

/**
 * Subgroup findUniqueOrThrow
 */
export type SubgroupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter, which Subgroup to fetch.
   */
  where: Prisma.SubgroupWhereUniqueInput
}

/**
 * Subgroup findFirst
 */
export type SubgroupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter, which Subgroup to fetch.
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subgroups to fetch.
   */
  orderBy?: Prisma.SubgroupOrderByWithRelationInput | Prisma.SubgroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Subgroups.
   */
  cursor?: Prisma.SubgroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subgroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subgroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Subgroups.
   */
  distinct?: Prisma.SubgroupScalarFieldEnum | Prisma.SubgroupScalarFieldEnum[]
}

/**
 * Subgroup findFirstOrThrow
 */
export type SubgroupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter, which Subgroup to fetch.
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subgroups to fetch.
   */
  orderBy?: Prisma.SubgroupOrderByWithRelationInput | Prisma.SubgroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Subgroups.
   */
  cursor?: Prisma.SubgroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subgroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subgroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Subgroups.
   */
  distinct?: Prisma.SubgroupScalarFieldEnum | Prisma.SubgroupScalarFieldEnum[]
}

/**
 * Subgroup findMany
 */
export type SubgroupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter, which Subgroups to fetch.
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Subgroups to fetch.
   */
  orderBy?: Prisma.SubgroupOrderByWithRelationInput | Prisma.SubgroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Subgroups.
   */
  cursor?: Prisma.SubgroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Subgroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Subgroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Subgroups.
   */
  distinct?: Prisma.SubgroupScalarFieldEnum | Prisma.SubgroupScalarFieldEnum[]
}

/**
 * Subgroup create
 */
export type SubgroupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * The data needed to create a Subgroup.
   */
  data: Prisma.XOR<Prisma.SubgroupCreateInput, Prisma.SubgroupUncheckedCreateInput>
}

/**
 * Subgroup createMany
 */
export type SubgroupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Subgroups.
   */
  data: Prisma.SubgroupCreateManyInput | Prisma.SubgroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Subgroup createManyAndReturn
 */
export type SubgroupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * The data used to create many Subgroups.
   */
  data: Prisma.SubgroupCreateManyInput | Prisma.SubgroupCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Subgroup update
 */
export type SubgroupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * The data needed to update a Subgroup.
   */
  data: Prisma.XOR<Prisma.SubgroupUpdateInput, Prisma.SubgroupUncheckedUpdateInput>
  /**
   * Choose, which Subgroup to update.
   */
  where: Prisma.SubgroupWhereUniqueInput
}

/**
 * Subgroup updateMany
 */
export type SubgroupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Subgroups.
   */
  data: Prisma.XOR<Prisma.SubgroupUpdateManyMutationInput, Prisma.SubgroupUncheckedUpdateManyInput>
  /**
   * Filter which Subgroups to update
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * Limit how many Subgroups to update.
   */
  limit?: number
}

/**
 * Subgroup updateManyAndReturn
 */
export type SubgroupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * The data used to update Subgroups.
   */
  data: Prisma.XOR<Prisma.SubgroupUpdateManyMutationInput, Prisma.SubgroupUncheckedUpdateManyInput>
  /**
   * Filter which Subgroups to update
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * Limit how many Subgroups to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Subgroup upsert
 */
export type SubgroupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * The filter to search for the Subgroup to update in case it exists.
   */
  where: Prisma.SubgroupWhereUniqueInput
  /**
   * In case the Subgroup found by the `where` argument doesn't exist, create a new Subgroup with this data.
   */
  create: Prisma.XOR<Prisma.SubgroupCreateInput, Prisma.SubgroupUncheckedCreateInput>
  /**
   * In case the Subgroup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubgroupUpdateInput, Prisma.SubgroupUncheckedUpdateInput>
}

/**
 * Subgroup delete
 */
export type SubgroupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
  /**
   * Filter which Subgroup to delete.
   */
  where: Prisma.SubgroupWhereUniqueInput
}

/**
 * Subgroup deleteMany
 */
export type SubgroupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Subgroups to delete
   */
  where?: Prisma.SubgroupWhereInput
  /**
   * Limit how many Subgroups to delete.
   */
  limit?: number
}

/**
 * Subgroup.knowledgeItems
 */
export type Subgroup$knowledgeItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeItem
   */
  select?: Prisma.KnowledgeItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeItem
   */
  omit?: Prisma.KnowledgeItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeItemInclude<ExtArgs> | null
  where?: Prisma.KnowledgeItemWhereInput
  orderBy?: Prisma.KnowledgeItemOrderByWithRelationInput | Prisma.KnowledgeItemOrderByWithRelationInput[]
  cursor?: Prisma.KnowledgeItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KnowledgeItemScalarFieldEnum | Prisma.KnowledgeItemScalarFieldEnum[]
}

/**
 * Subgroup without action
 */
export type SubgroupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subgroup
   */
  select?: Prisma.SubgroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subgroup
   */
  omit?: Prisma.SubgroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubgroupInclude<ExtArgs> | null
}
