/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ThemeSuggestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.ts";
import type * as Prisma from "../internal/prismaNamespace.ts";

/**
 * Model ThemeSuggestion
 *
 */
export type ThemeSuggestionModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ThemeSuggestionPayload>;

export type AggregateThemeSuggestion = {
  _count: ThemeSuggestionCountAggregateOutputType | null;
  _min: ThemeSuggestionMinAggregateOutputType | null;
  _max: ThemeSuggestionMaxAggregateOutputType | null;
};

export type ThemeSuggestionMinAggregateOutputType = {
  id: string | null;
  suggestedName: string | null;
  status: $Enums.SuggestionStatus | null;
  userId: string | null;
  communityId: string | null;
  createdAt: Date | null;
};

export type ThemeSuggestionMaxAggregateOutputType = {
  id: string | null;
  suggestedName: string | null;
  status: $Enums.SuggestionStatus | null;
  userId: string | null;
  communityId: string | null;
  createdAt: Date | null;
};

export type ThemeSuggestionCountAggregateOutputType = {
  id: number;
  suggestedName: number;
  status: number;
  userId: number;
  communityId: number;
  createdAt: number;
  _all: number;
};

export type ThemeSuggestionMinAggregateInputType = {
  id?: true;
  suggestedName?: true;
  status?: true;
  userId?: true;
  communityId?: true;
  createdAt?: true;
};

export type ThemeSuggestionMaxAggregateInputType = {
  id?: true;
  suggestedName?: true;
  status?: true;
  userId?: true;
  communityId?: true;
  createdAt?: true;
};

export type ThemeSuggestionCountAggregateInputType = {
  id?: true;
  suggestedName?: true;
  status?: true;
  userId?: true;
  communityId?: true;
  createdAt?: true;
  _all?: true;
};

export type ThemeSuggestionAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ThemeSuggestion to aggregate.
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThemeSuggestions to fetch.
   */
  orderBy?:
    | Prisma.ThemeSuggestionOrderByWithRelationInput
    | Prisma.ThemeSuggestionOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ThemeSuggestionWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThemeSuggestions from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThemeSuggestions.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ThemeSuggestions
   **/
  _count?: true | ThemeSuggestionCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ThemeSuggestionMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ThemeSuggestionMaxAggregateInputType;
};

export type GetThemeSuggestionAggregateType<T extends ThemeSuggestionAggregateArgs> = {
  [P in keyof T & keyof AggregateThemeSuggestion]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateThemeSuggestion[P]>
    : Prisma.GetScalarType<T[P], AggregateThemeSuggestion[P]>;
};

export type ThemeSuggestionGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ThemeSuggestionWhereInput;
  orderBy?:
    | Prisma.ThemeSuggestionOrderByWithAggregationInput
    | Prisma.ThemeSuggestionOrderByWithAggregationInput[];
  by: Prisma.ThemeSuggestionScalarFieldEnum[] | Prisma.ThemeSuggestionScalarFieldEnum;
  having?: Prisma.ThemeSuggestionScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ThemeSuggestionCountAggregateInputType | true;
  _min?: ThemeSuggestionMinAggregateInputType;
  _max?: ThemeSuggestionMaxAggregateInputType;
};

export type ThemeSuggestionGroupByOutputType = {
  id: string;
  suggestedName: string;
  status: $Enums.SuggestionStatus;
  userId: string;
  communityId: string;
  createdAt: Date;
  _count: ThemeSuggestionCountAggregateOutputType | null;
  _min: ThemeSuggestionMinAggregateOutputType | null;
  _max: ThemeSuggestionMaxAggregateOutputType | null;
};

export type GetThemeSuggestionGroupByPayload<T extends ThemeSuggestionGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ThemeSuggestionGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof ThemeSuggestionGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ThemeSuggestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ThemeSuggestionGroupByOutputType[P]>;
      }
    >
  >;

export type ThemeSuggestionWhereInput = {
  AND?: Prisma.ThemeSuggestionWhereInput | Prisma.ThemeSuggestionWhereInput[];
  OR?: Prisma.ThemeSuggestionWhereInput[];
  NOT?: Prisma.ThemeSuggestionWhereInput | Prisma.ThemeSuggestionWhereInput[];
  id?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  suggestedName?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  status?: Prisma.EnumSuggestionStatusFilter<"ThemeSuggestion"> | $Enums.SuggestionStatus;
  userId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  communityId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  createdAt?: Prisma.DateTimeFilter<"ThemeSuggestion"> | Date | string;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  community?: Prisma.XOR<Prisma.CommunityScalarRelationFilter, Prisma.CommunityWhereInput>;
};

export type ThemeSuggestionOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  suggestedName?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  communityId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
  community?: Prisma.CommunityOrderByWithRelationInput;
};

export type ThemeSuggestionWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.ThemeSuggestionWhereInput | Prisma.ThemeSuggestionWhereInput[];
    OR?: Prisma.ThemeSuggestionWhereInput[];
    NOT?: Prisma.ThemeSuggestionWhereInput | Prisma.ThemeSuggestionWhereInput[];
    suggestedName?: Prisma.StringFilter<"ThemeSuggestion"> | string;
    status?: Prisma.EnumSuggestionStatusFilter<"ThemeSuggestion"> | $Enums.SuggestionStatus;
    userId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
    communityId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
    createdAt?: Prisma.DateTimeFilter<"ThemeSuggestion"> | Date | string;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    community?: Prisma.XOR<Prisma.CommunityScalarRelationFilter, Prisma.CommunityWhereInput>;
  },
  "id"
>;

export type ThemeSuggestionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  suggestedName?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  communityId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.ThemeSuggestionCountOrderByAggregateInput;
  _max?: Prisma.ThemeSuggestionMaxOrderByAggregateInput;
  _min?: Prisma.ThemeSuggestionMinOrderByAggregateInput;
};

export type ThemeSuggestionScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ThemeSuggestionScalarWhereWithAggregatesInput
    | Prisma.ThemeSuggestionScalarWhereWithAggregatesInput[];
  OR?: Prisma.ThemeSuggestionScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ThemeSuggestionScalarWhereWithAggregatesInput
    | Prisma.ThemeSuggestionScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"ThemeSuggestion"> | string;
  suggestedName?: Prisma.StringWithAggregatesFilter<"ThemeSuggestion"> | string;
  status?:
    | Prisma.EnumSuggestionStatusWithAggregatesFilter<"ThemeSuggestion">
    | $Enums.SuggestionStatus;
  userId?: Prisma.StringWithAggregatesFilter<"ThemeSuggestion"> | string;
  communityId?: Prisma.StringWithAggregatesFilter<"ThemeSuggestion"> | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ThemeSuggestion"> | Date | string;
};

export type ThemeSuggestionCreateInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  createdAt: Date | string;
  user: Prisma.UserCreateNestedOneWithoutThemeSuggestionsInput;
  community: Prisma.CommunityCreateNestedOneWithoutThemeSuggestionsInput;
};

export type ThemeSuggestionUncheckedCreateInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  userId: string;
  communityId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutThemeSuggestionsNestedInput;
  community?: Prisma.CommunityUpdateOneRequiredWithoutThemeSuggestionsNestedInput;
};

export type ThemeSuggestionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  communityId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionCreateManyInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  userId: string;
  communityId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  communityId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionListRelationFilter = {
  every?: Prisma.ThemeSuggestionWhereInput;
  some?: Prisma.ThemeSuggestionWhereInput;
  none?: Prisma.ThemeSuggestionWhereInput;
};

export type ThemeSuggestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type ThemeSuggestionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  suggestedName?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  communityId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ThemeSuggestionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  suggestedName?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  communityId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ThemeSuggestionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  suggestedName?: Prisma.SortOrder;
  status?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  communityId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ThemeSuggestionCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutUserInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
      >
    | Prisma.ThemeSuggestionCreateWithoutUserInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyUserInputEnvelope;
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
};

export type ThemeSuggestionUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutUserInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
      >
    | Prisma.ThemeSuggestionCreateWithoutUserInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyUserInputEnvelope;
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
};

export type ThemeSuggestionUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutUserInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
      >
    | Prisma.ThemeSuggestionCreateWithoutUserInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyUserInputEnvelope;
  set?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  disconnect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  delete?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  update?:
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutUserInput
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
};

export type ThemeSuggestionUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutUserInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
      >
    | Prisma.ThemeSuggestionCreateWithoutUserInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyUserInputEnvelope;
  set?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  disconnect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  delete?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  update?:
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutUserInput
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
};

export type ThemeSuggestionCreateNestedManyWithoutCommunityInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutCommunityInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
      >
    | Prisma.ThemeSuggestionCreateWithoutCommunityInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyCommunityInputEnvelope;
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
};

export type ThemeSuggestionUncheckedCreateNestedManyWithoutCommunityInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutCommunityInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
      >
    | Prisma.ThemeSuggestionCreateWithoutCommunityInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyCommunityInputEnvelope;
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
};

export type ThemeSuggestionUpdateManyWithoutCommunityNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutCommunityInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
      >
    | Prisma.ThemeSuggestionCreateWithoutCommunityInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput[];
  upsert?:
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutCommunityInput
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutCommunityInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyCommunityInputEnvelope;
  set?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  disconnect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  delete?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  update?:
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutCommunityInput
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutCommunityInput[];
  updateMany?:
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutCommunityInput
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutCommunityInput[];
  deleteMany?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
};

export type ThemeSuggestionUncheckedUpdateManyWithoutCommunityNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThemeSuggestionCreateWithoutCommunityInput,
        Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
      >
    | Prisma.ThemeSuggestionCreateWithoutCommunityInput[]
    | Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput[];
  connectOrCreate?:
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput
    | Prisma.ThemeSuggestionCreateOrConnectWithoutCommunityInput[];
  upsert?:
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutCommunityInput
    | Prisma.ThemeSuggestionUpsertWithWhereUniqueWithoutCommunityInput[];
  createMany?: Prisma.ThemeSuggestionCreateManyCommunityInputEnvelope;
  set?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  disconnect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  delete?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  connect?: Prisma.ThemeSuggestionWhereUniqueInput | Prisma.ThemeSuggestionWhereUniqueInput[];
  update?:
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutCommunityInput
    | Prisma.ThemeSuggestionUpdateWithWhereUniqueWithoutCommunityInput[];
  updateMany?:
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutCommunityInput
    | Prisma.ThemeSuggestionUpdateManyWithWhereWithoutCommunityInput[];
  deleteMany?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
};

export type EnumSuggestionStatusFieldUpdateOperationsInput = {
  set?: $Enums.SuggestionStatus;
};

export type ThemeSuggestionCreateWithoutUserInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  createdAt: Date | string;
  community: Prisma.CommunityCreateNestedOneWithoutThemeSuggestionsInput;
};

export type ThemeSuggestionUncheckedCreateWithoutUserInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  communityId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionCreateOrConnectWithoutUserInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ThemeSuggestionCreateWithoutUserInput,
    Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
  >;
};

export type ThemeSuggestionCreateManyUserInputEnvelope = {
  data: Prisma.ThemeSuggestionCreateManyUserInput | Prisma.ThemeSuggestionCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type ThemeSuggestionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateWithoutUserInput,
    Prisma.ThemeSuggestionUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.ThemeSuggestionCreateWithoutUserInput,
    Prisma.ThemeSuggestionUncheckedCreateWithoutUserInput
  >;
};

export type ThemeSuggestionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateWithoutUserInput,
    Prisma.ThemeSuggestionUncheckedUpdateWithoutUserInput
  >;
};

export type ThemeSuggestionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ThemeSuggestionScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateManyMutationInput,
    Prisma.ThemeSuggestionUncheckedUpdateManyWithoutUserInput
  >;
};

export type ThemeSuggestionScalarWhereInput = {
  AND?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
  OR?: Prisma.ThemeSuggestionScalarWhereInput[];
  NOT?: Prisma.ThemeSuggestionScalarWhereInput | Prisma.ThemeSuggestionScalarWhereInput[];
  id?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  suggestedName?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  status?: Prisma.EnumSuggestionStatusFilter<"ThemeSuggestion"> | $Enums.SuggestionStatus;
  userId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  communityId?: Prisma.StringFilter<"ThemeSuggestion"> | string;
  createdAt?: Prisma.DateTimeFilter<"ThemeSuggestion"> | Date | string;
};

export type ThemeSuggestionCreateWithoutCommunityInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  createdAt: Date | string;
  user: Prisma.UserCreateNestedOneWithoutThemeSuggestionsInput;
};

export type ThemeSuggestionUncheckedCreateWithoutCommunityInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  userId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionCreateOrConnectWithoutCommunityInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ThemeSuggestionCreateWithoutCommunityInput,
    Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
  >;
};

export type ThemeSuggestionCreateManyCommunityInputEnvelope = {
  data:
    | Prisma.ThemeSuggestionCreateManyCommunityInput
    | Prisma.ThemeSuggestionCreateManyCommunityInput[];
  skipDuplicates?: boolean;
};

export type ThemeSuggestionUpsertWithWhereUniqueWithoutCommunityInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateWithoutCommunityInput,
    Prisma.ThemeSuggestionUncheckedUpdateWithoutCommunityInput
  >;
  create: Prisma.XOR<
    Prisma.ThemeSuggestionCreateWithoutCommunityInput,
    Prisma.ThemeSuggestionUncheckedCreateWithoutCommunityInput
  >;
};

export type ThemeSuggestionUpdateWithWhereUniqueWithoutCommunityInput = {
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateWithoutCommunityInput,
    Prisma.ThemeSuggestionUncheckedUpdateWithoutCommunityInput
  >;
};

export type ThemeSuggestionUpdateManyWithWhereWithoutCommunityInput = {
  where: Prisma.ThemeSuggestionScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateManyMutationInput,
    Prisma.ThemeSuggestionUncheckedUpdateManyWithoutCommunityInput
  >;
};

export type ThemeSuggestionCreateManyUserInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  communityId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  community?: Prisma.CommunityUpdateOneRequiredWithoutThemeSuggestionsNestedInput;
};

export type ThemeSuggestionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  communityId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  communityId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionCreateManyCommunityInput = {
  id?: string;
  suggestedName: string;
  status?: $Enums.SuggestionStatus;
  userId: string;
  createdAt: Date | string;
};

export type ThemeSuggestionUpdateWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutThemeSuggestionsNestedInput;
};

export type ThemeSuggestionUncheckedUpdateWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionUncheckedUpdateManyWithoutCommunityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  suggestedName?: Prisma.StringFieldUpdateOperationsInput | string;
  status?: Prisma.EnumSuggestionStatusFieldUpdateOperationsInput | $Enums.SuggestionStatus;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ThemeSuggestionSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    suggestedName?: boolean;
    status?: boolean;
    userId?: boolean;
    communityId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["themeSuggestion"]
>;

export type ThemeSuggestionSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    suggestedName?: boolean;
    status?: boolean;
    userId?: boolean;
    communityId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["themeSuggestion"]
>;

export type ThemeSuggestionSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    suggestedName?: boolean;
    status?: boolean;
    userId?: boolean;
    communityId?: boolean;
    createdAt?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["themeSuggestion"]
>;

export type ThemeSuggestionSelectScalar = {
  id?: boolean;
  suggestedName?: boolean;
  status?: boolean;
  userId?: boolean;
  communityId?: boolean;
  createdAt?: boolean;
};

export type ThemeSuggestionOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "suggestedName" | "status" | "userId" | "communityId" | "createdAt",
  ExtArgs["result"]["themeSuggestion"]
>;
export type ThemeSuggestionInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
};
export type ThemeSuggestionIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
};
export type ThemeSuggestionIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  community?: boolean | Prisma.CommunityDefaultArgs<ExtArgs>;
};

export type $ThemeSuggestionPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "ThemeSuggestion";
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
    community: Prisma.$CommunityPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      suggestedName: string;
      status: $Enums.SuggestionStatus;
      userId: string;
      communityId: string;
      createdAt: Date;
    },
    ExtArgs["result"]["themeSuggestion"]
  >;
  composites: {};
};

export type ThemeSuggestionGetPayload<
  S extends boolean | null | undefined | ThemeSuggestionDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ThemeSuggestionPayload, S>;

export type ThemeSuggestionCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ThemeSuggestionFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: ThemeSuggestionCountAggregateInputType | true;
};

export interface ThemeSuggestionDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["ThemeSuggestion"];
    meta: { name: "ThemeSuggestion" };
  };
  /**
   * Find zero or one ThemeSuggestion that matches the filter.
   * @param {ThemeSuggestionFindUniqueArgs} args - Arguments to find a ThemeSuggestion
   * @example
   * // Get one ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ThemeSuggestionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ThemeSuggestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ThemeSuggestionFindUniqueOrThrowArgs} args - Arguments to find a ThemeSuggestion
   * @example
   * // Get one ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ThemeSuggestionFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ThemeSuggestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionFindFirstArgs} args - Arguments to find a ThemeSuggestion
   * @example
   * // Get one ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ThemeSuggestionFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ThemeSuggestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionFindFirstOrThrowArgs} args - Arguments to find a ThemeSuggestion
   * @example
   * // Get one ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ThemeSuggestionFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ThemeSuggestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ThemeSuggestions
   * const themeSuggestions = await prisma.themeSuggestion.findMany()
   *
   * // Get first 10 ThemeSuggestions
   * const themeSuggestions = await prisma.themeSuggestion.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const themeSuggestionWithIdOnly = await prisma.themeSuggestion.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ThemeSuggestionFindManyArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ThemeSuggestion.
   * @param {ThemeSuggestionCreateArgs} args - Arguments to create a ThemeSuggestion.
   * @example
   * // Create one ThemeSuggestion
   * const ThemeSuggestion = await prisma.themeSuggestion.create({
   *   data: {
   *     // ... data to create a ThemeSuggestion
   *   }
   * })
   *
   */
  create<T extends ThemeSuggestionCreateArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ThemeSuggestions.
   * @param {ThemeSuggestionCreateManyArgs} args - Arguments to create many ThemeSuggestions.
   * @example
   * // Create many ThemeSuggestions
   * const themeSuggestion = await prisma.themeSuggestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ThemeSuggestionCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ThemeSuggestions and returns the data saved in the database.
   * @param {ThemeSuggestionCreateManyAndReturnArgs} args - Arguments to create many ThemeSuggestions.
   * @example
   * // Create many ThemeSuggestions
   * const themeSuggestion = await prisma.themeSuggestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ThemeSuggestions and only return the `id`
   * const themeSuggestionWithIdOnly = await prisma.themeSuggestion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ThemeSuggestionCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a ThemeSuggestion.
   * @param {ThemeSuggestionDeleteArgs} args - Arguments to delete one ThemeSuggestion.
   * @example
   * // Delete one ThemeSuggestion
   * const ThemeSuggestion = await prisma.themeSuggestion.delete({
   *   where: {
   *     // ... filter to delete one ThemeSuggestion
   *   }
   * })
   *
   */
  delete<T extends ThemeSuggestionDeleteArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ThemeSuggestion.
   * @param {ThemeSuggestionUpdateArgs} args - Arguments to update one ThemeSuggestion.
   * @example
   * // Update one ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ThemeSuggestionUpdateArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ThemeSuggestions.
   * @param {ThemeSuggestionDeleteManyArgs} args - Arguments to filter ThemeSuggestions to delete.
   * @example
   * // Delete a few ThemeSuggestions
   * const { count } = await prisma.themeSuggestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ThemeSuggestionDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ThemeSuggestionDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ThemeSuggestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ThemeSuggestions
   * const themeSuggestion = await prisma.themeSuggestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ThemeSuggestionUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ThemeSuggestions and returns the data updated in the database.
   * @param {ThemeSuggestionUpdateManyAndReturnArgs} args - Arguments to update many ThemeSuggestions.
   * @example
   * // Update many ThemeSuggestions
   * const themeSuggestion = await prisma.themeSuggestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ThemeSuggestions and only return the `id`
   * const themeSuggestionWithIdOnly = await prisma.themeSuggestion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ThemeSuggestionUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one ThemeSuggestion.
   * @param {ThemeSuggestionUpsertArgs} args - Arguments to update or create a ThemeSuggestion.
   * @example
   * // Update or create a ThemeSuggestion
   * const themeSuggestion = await prisma.themeSuggestion.upsert({
   *   create: {
   *     // ... data to create a ThemeSuggestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ThemeSuggestion we want to update
   *   }
   * })
   */
  upsert<T extends ThemeSuggestionUpsertArgs>(
    args: Prisma.SelectSubset<T, ThemeSuggestionUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ThemeSuggestionClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThemeSuggestionPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ThemeSuggestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionCountArgs} args - Arguments to filter ThemeSuggestions to count.
   * @example
   * // Count the number of ThemeSuggestions
   * const count = await prisma.themeSuggestion.count({
   *   where: {
   *     // ... the filter for the ThemeSuggestions we want to count
   *   }
   * })
   **/
  count<T extends ThemeSuggestionCountArgs>(
    args?: Prisma.Subset<T, ThemeSuggestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], ThemeSuggestionCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ThemeSuggestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ThemeSuggestionAggregateArgs>(
    args: Prisma.Subset<T, ThemeSuggestionAggregateArgs>,
  ): Prisma.PrismaPromise<GetThemeSuggestionAggregateType<T>>;

  /**
   * Group by ThemeSuggestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThemeSuggestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ThemeSuggestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ThemeSuggestionGroupByArgs["orderBy"] }
      : { orderBy?: ThemeSuggestionGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ThemeSuggestionGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors
    ? GetThemeSuggestionGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ThemeSuggestion model
   */
  readonly fields: ThemeSuggestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ThemeSuggestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ThemeSuggestionClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  community<T extends Prisma.CommunityDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.CommunityDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__CommunityClient<
    | runtime.Types.Result.GetResult<
        Prisma.$CommunityPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ThemeSuggestion model
 */
export interface ThemeSuggestionFieldRefs {
  readonly id: Prisma.FieldRef<"ThemeSuggestion", "String">;
  readonly suggestedName: Prisma.FieldRef<"ThemeSuggestion", "String">;
  readonly status: Prisma.FieldRef<"ThemeSuggestion", "SuggestionStatus">;
  readonly userId: Prisma.FieldRef<"ThemeSuggestion", "String">;
  readonly communityId: Prisma.FieldRef<"ThemeSuggestion", "String">;
  readonly createdAt: Prisma.FieldRef<"ThemeSuggestion", "DateTime">;
}

// Custom InputTypes
/**
 * ThemeSuggestion findUnique
 */
export type ThemeSuggestionFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter, which ThemeSuggestion to fetch.
   */
  where: Prisma.ThemeSuggestionWhereUniqueInput;
};

/**
 * ThemeSuggestion findUniqueOrThrow
 */
export type ThemeSuggestionFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter, which ThemeSuggestion to fetch.
   */
  where: Prisma.ThemeSuggestionWhereUniqueInput;
};

/**
 * ThemeSuggestion findFirst
 */
export type ThemeSuggestionFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter, which ThemeSuggestion to fetch.
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThemeSuggestions to fetch.
   */
  orderBy?:
    | Prisma.ThemeSuggestionOrderByWithRelationInput
    | Prisma.ThemeSuggestionOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ThemeSuggestions.
   */
  cursor?: Prisma.ThemeSuggestionWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThemeSuggestions from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThemeSuggestions.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ThemeSuggestions.
   */
  distinct?: Prisma.ThemeSuggestionScalarFieldEnum | Prisma.ThemeSuggestionScalarFieldEnum[];
};

/**
 * ThemeSuggestion findFirstOrThrow
 */
export type ThemeSuggestionFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter, which ThemeSuggestion to fetch.
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThemeSuggestions to fetch.
   */
  orderBy?:
    | Prisma.ThemeSuggestionOrderByWithRelationInput
    | Prisma.ThemeSuggestionOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ThemeSuggestions.
   */
  cursor?: Prisma.ThemeSuggestionWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThemeSuggestions from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThemeSuggestions.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ThemeSuggestions.
   */
  distinct?: Prisma.ThemeSuggestionScalarFieldEnum | Prisma.ThemeSuggestionScalarFieldEnum[];
};

/**
 * ThemeSuggestion findMany
 */
export type ThemeSuggestionFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter, which ThemeSuggestions to fetch.
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThemeSuggestions to fetch.
   */
  orderBy?:
    | Prisma.ThemeSuggestionOrderByWithRelationInput
    | Prisma.ThemeSuggestionOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ThemeSuggestions.
   */
  cursor?: Prisma.ThemeSuggestionWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThemeSuggestions from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThemeSuggestions.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ThemeSuggestions.
   */
  distinct?: Prisma.ThemeSuggestionScalarFieldEnum | Prisma.ThemeSuggestionScalarFieldEnum[];
};

/**
 * ThemeSuggestion create
 */
export type ThemeSuggestionCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * The data needed to create a ThemeSuggestion.
   */
  data: Prisma.XOR<Prisma.ThemeSuggestionCreateInput, Prisma.ThemeSuggestionUncheckedCreateInput>;
};

/**
 * ThemeSuggestion createMany
 */
export type ThemeSuggestionCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ThemeSuggestions.
   */
  data: Prisma.ThemeSuggestionCreateManyInput | Prisma.ThemeSuggestionCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ThemeSuggestion createManyAndReturn
 */
export type ThemeSuggestionCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * The data used to create many ThemeSuggestions.
   */
  data: Prisma.ThemeSuggestionCreateManyInput | Prisma.ThemeSuggestionCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ThemeSuggestion update
 */
export type ThemeSuggestionUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * The data needed to update a ThemeSuggestion.
   */
  data: Prisma.XOR<Prisma.ThemeSuggestionUpdateInput, Prisma.ThemeSuggestionUncheckedUpdateInput>;
  /**
   * Choose, which ThemeSuggestion to update.
   */
  where: Prisma.ThemeSuggestionWhereUniqueInput;
};

/**
 * ThemeSuggestion updateMany
 */
export type ThemeSuggestionUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ThemeSuggestions.
   */
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateManyMutationInput,
    Prisma.ThemeSuggestionUncheckedUpdateManyInput
  >;
  /**
   * Filter which ThemeSuggestions to update
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * Limit how many ThemeSuggestions to update.
   */
  limit?: number;
};

/**
 * ThemeSuggestion updateManyAndReturn
 */
export type ThemeSuggestionUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * The data used to update ThemeSuggestions.
   */
  data: Prisma.XOR<
    Prisma.ThemeSuggestionUpdateManyMutationInput,
    Prisma.ThemeSuggestionUncheckedUpdateManyInput
  >;
  /**
   * Filter which ThemeSuggestions to update
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * Limit how many ThemeSuggestions to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ThemeSuggestion upsert
 */
export type ThemeSuggestionUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * The filter to search for the ThemeSuggestion to update in case it exists.
   */
  where: Prisma.ThemeSuggestionWhereUniqueInput;
  /**
   * In case the ThemeSuggestion found by the `where` argument doesn't exist, create a new ThemeSuggestion with this data.
   */
  create: Prisma.XOR<Prisma.ThemeSuggestionCreateInput, Prisma.ThemeSuggestionUncheckedCreateInput>;
  /**
   * In case the ThemeSuggestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ThemeSuggestionUpdateInput, Prisma.ThemeSuggestionUncheckedUpdateInput>;
};

/**
 * ThemeSuggestion delete
 */
export type ThemeSuggestionDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
  /**
   * Filter which ThemeSuggestion to delete.
   */
  where: Prisma.ThemeSuggestionWhereUniqueInput;
};

/**
 * ThemeSuggestion deleteMany
 */
export type ThemeSuggestionDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ThemeSuggestions to delete
   */
  where?: Prisma.ThemeSuggestionWhereInput;
  /**
   * Limit how many ThemeSuggestions to delete.
   */
  limit?: number;
};

/**
 * ThemeSuggestion without action
 */
export type ThemeSuggestionDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThemeSuggestion
   */
  select?: Prisma.ThemeSuggestionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThemeSuggestion
   */
  omit?: Prisma.ThemeSuggestionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThemeSuggestionInclude<ExtArgs> | null;
};
