
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Community: 'Community',
  CommunityMember: 'CommunityMember',
  Subgroup: 'Subgroup',
  KnowledgeItem: 'KnowledgeItem',
  Event: 'Event',
  EventAttendee: 'EventAttendee',
  ThemeSuggestion: 'ThemeSuggestion'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  rainbowUserId: 'rainbowUserId',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CommunityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt'
} as const

export type CommunityScalarFieldEnum = (typeof CommunityScalarFieldEnum)[keyof typeof CommunityScalarFieldEnum]


export const CommunityMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  communityId: 'communityId',
  role: 'role',
  joinedAt: 'joinedAt',
  warningCount: 'warningCount'
} as const

export type CommunityMemberScalarFieldEnum = (typeof CommunityMemberScalarFieldEnum)[keyof typeof CommunityMemberScalarFieldEnum]


export const SubgroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  theme: 'theme',
  communityId: 'communityId',
  rainbowBubbleId: 'rainbowBubbleId',
  createdAt: 'createdAt'
} as const

export type SubgroupScalarFieldEnum = (typeof SubgroupScalarFieldEnum)[keyof typeof SubgroupScalarFieldEnum]


export const KnowledgeItemScalarFieldEnum = {
  id: 'id',
  subgroupId: 'subgroupId',
  authorId: 'authorId',
  rainbowMessageId: 'rainbowMessageId',
  content: 'content',
  tags: 'tags',
  isPinned: 'isPinned',
  lastIndexedAt: 'lastIndexedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KnowledgeItemScalarFieldEnum = (typeof KnowledgeItemScalarFieldEnum)[keyof typeof KnowledgeItemScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  communityId: 'communityId',
  startTime: 'startTime',
  endTime: 'endTime',
  conferenceLink: 'conferenceLink',
  createdAt: 'createdAt'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const EventAttendeeScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId'
} as const

export type EventAttendeeScalarFieldEnum = (typeof EventAttendeeScalarFieldEnum)[keyof typeof EventAttendeeScalarFieldEnum]


export const ThemeSuggestionScalarFieldEnum = {
  id: 'id',
  suggestedName: 'suggestedName',
  status: 'status',
  userId: 'userId',
  communityId: 'communityId',
  createdAt: 'createdAt'
} as const

export type ThemeSuggestionScalarFieldEnum = (typeof ThemeSuggestionScalarFieldEnum)[keyof typeof ThemeSuggestionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

